version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webcrud
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d webcrud"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  backend:
    build: 
      context: ./backend/dev-project
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/webcrud
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_GENERATE-DDL=true
    ports: 
      - 8080:8080

  frontend:
      build: 
        context: ./frontend/dev-project
        dockerfile: Dockerfile
      restart: always
      volumes: 
          - ./frontend:/app/"
          - /app/node_modules
      ports: 
          - "5173:5173"